/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef serviceSync_CONSTANTS_H
#define serviceSync_CONSTANTS_H

#include "serviceSync_types.h"



class serviceSyncConstants {
 public:
  serviceSyncConstants();

};

extern const serviceSyncConstants g_serviceSync_constants;



#endif
