/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef service_TYPES_H
#define service_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace serviceProvider {

class sensorData;

typedef struct _sensorData__isset {
  _sensorData__isset() : id(false), value(false), timestamp(false) {}
  bool id :1;
  bool value :1;
  bool timestamp :1;
} _sensorData__isset;

class sensorData : public virtual ::apache::thrift::TBase {
 public:

  sensorData(const sensorData&);
  sensorData& operator=(const sensorData&);
  sensorData() : id(0), value(0), timestamp() {
  }

  virtual ~sensorData() noexcept;
  int32_t id;
  int32_t value;
  std::string timestamp;

  _sensorData__isset __isset;

  void __set_id(const int32_t val);

  void __set_value(const int32_t val);

  void __set_timestamp(const std::string& val);

  bool operator == (const sensorData & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    return true;
  }
  bool operator != (const sensorData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const sensorData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(sensorData &a, sensorData &b);

std::ostream& operator<<(std::ostream& out, const sensorData& obj);

} // namespace

#endif
